###查询
GET http://localhost:8083/byrcjt/user/findAll
content-type:application/json

{
}

###删除
GET http://localhost:8080/user/del
content-type:application/json;charset=UTF-8

{
  "id":5
}

###添加
GET http://localhost:8080/user/add
content-type:application/json

{
  "id":"1",
  "name": " ",
  "sex": "男"
}

###