###查询
GET http://localhost:8083/byrcjt/user/findAll
content-type:application/json

{
}

###删除
GET http://localhost:8083/byrcjt/user/del
content-type:application/json;charset=UTF-8

{
  "id":0
}

###添加
GET http://localhost:8083/byrcjt/user/add
content-type:application/json

{
  "id":"1",
  "name": "赵八",
  "age": "18"
}

###